# +------------------+
# | AdminCore Config |
# +------------------+
#Stops the server when it starts if the plugin is made for a different version. Can be useful if you forget to update.
killwhenoutdated: false
#The title of server-wide announcements. The message you announce will be the subtitle.
announcementtitle: 'A Very Cool Announcement'
#The message to send to players when a staff member enters staffmode. Use &{color code} to format the text to match your actual disconnect message. Colors should come before bolding or italics. Use %p% to specify the name of the staff member. For example: '&e%p% left the game.'
pseudodisconnect:
  send-message: true
  message: '&e%p% left the game.'
#The message to send to players when a staff member leaves staffmode. Use &{color code} to format the text to match your actual disconnect message. Colors should come before bolding or italics. Use %p% to specify the name of the staff member. For example: '&e%p% left the game.'
pseudojoin:
  send-message: true
  message: '&e%p% joined the game.'
#Settings for /status
#Log determines whether the corresponding information will be shown to the player
#Protect-sensitive will hide the ip and port from anyone without the "admincore.admin" permission
serverstatus:
  protect-sensitive: true
  serverVersion:
    log: true
  buildInformation:
    log: true
  ip:
    log: true
  port:
    log: true
  playerCount:
    log: true
  tps:
    log:
      one-minute: true
      five-minutes: true
      fifteen-minutes: true
  uptime:
    log: true
  ram:
    log: true
  ping:
    log: true
