# Admincore Config
# First time here or just want a guide? Head over to https://rudrecciah.dev/admincore/wiki/setup. It'll take you on a simple, step by step guide on setting up Admincore.
# Updating? Head over to https://rudrecciah.dev/admincore/wiki/updating. It'll take you on a simple, step by step guide on updating Admincore and its config.
broadcasts: true
announcementtitle: 'A Very Cool Announcement'
bot:
  enable: false
  token: ''
  presence:
    action: 0
    url: 'https://rudrecciah.dev/admincore'
    status: 'staff members'
  prefix: '/'
  channels:
    admin: ''
    trusted: ''
    staff: ''
  commands:
    announce: true
    freeze: true
    unfreeze: true
    stats: true
    history: true
    aliases: true
chatlink:
  send:
    enable: false
    channel: ''
  get:
    enable: true
    token: ''
webhook:
  customName: false
  name: 'jams'
  icon: 'https://thumbnailer.mixcloud.com/unsafe/300x300/extaudio/9/0/d/1/3f46-6ee1-4ccd-b21c-14ed5bbc1703.jpg'
  errorLogger:
    use: false
    reload: true
    token: ''
  reportLogger:
    use: false
    token: ''
  banLogger:
    use: false
    token: ''
  muteLogger:
    use: false
    token: ''
  appealLogger:
    use: false
    token: ''
  kickLogger:
    use: false
    token: ''
  broadcastLogger:
    use: false
    token: ''
staffmode:
  resetgamemode: true
  tptospawn:
    teleport: true
    use-spawn-cmd: false
    spawn-cmd: 'spawn'
    location:
      world: 'world'
      coordinates:
        x: 12.0
        y: 8.0
        z: 0.0
        yaw: -90
        pitch: 0
  pseudodisconnect:
    send-message: true
    message: '&e%p% left the game'
  pseudojoin:
    send-message: true
    message: '&e%p% joined the game'
  punishment:
    report:
      reasons:
        1: 'Cheating'
        2: 'Chat Abuse'
        3: 'idk fookin botum geah moates'
        4: 'Chargebacks'
        5: 'DDoS Threats'
        6: 'Name Abuse'
        7: 'Player Threats'
        8: ''
      autoclose:
        close-on-mute: true
        close-on-tempban: true
        close-on-ban: true
        close-on-ip-ban: true
      teleport: true
    ban:
      reasons:
        1: 'Cheating'
        2: 'Chat Abuse'
        3: 'idk fookin botum geah moates'
        4: 'Chargebacks'
        5: 'DDoS Threats'
        6: 'Name Abuse'
        7: 'Player Threats'
        8: ''
      tempban-length: 30
      ip-ban: true
    mute:
      reasons:
        1: 'Cheating'
        2: 'Chat Abuse'
        3: 'idk fookin botum geah moates'
        4: 'Chargebacks'
        5: 'DDoS Threats'
        6: 'Name Abuse'
        7: 'Player Threats'
        8: ''
      mute-length: 30
    appeals:
      mute:
        allow-appeals: true
        message: 'To appeal your mute, go to https://example.com/appeals.'
      tempban:
        allow-appeals: true
        message: 'To appeal your ban, go to https://example.com/appeals.'
      ban:
        allow-appeals: true
        message: 'To appeal your ban, go to https://example.com/appeals.'
      ip-ban:
        allow-appeals: true
        message: 'To appeal your IP ban, go to https://example.com/appeals.'
      api:
        enable: false
        hostname: localhost
        port: 9090
  stats:
    api-key: ''
    public-networks: false
    strict: true
serverstatus:
  protect-sensitive: true
  serverVersion:
    log: true
  buildInformation:
    log: true
  ip:
    log: true
  port:
    log: true
  playerCount:
    log: true
  tps:
    log:
      one-minute: true
      five-minutes: true
      fifteen-minutes: true
  uptime:
    log: true
  ram:
    log: true
  ping:
    log: true
version: 3
