# +------------------+
# | AdminCore Config |
# +------------------+
killwhenoutdated: false
announcementtitle: 'A Very Cool Announcement'
logexceptions: true
webhook:
  #token is full url, not just id
  customName: true
  name: 'Admincore'
  icon: 'https://raw.githubusercontent.com/RudRecciah/Admin-Core/main/icons/logo.png'
  reportLogger:
    use: true
    token: 'a token'
  errorLogger:
    use: true
    token: 'a cool token'
  banLogger:
    use: true
    token: 'an even cooler token'
  muteLogger:
    use: true
    token: 'an even cooler token'
  chatLogger:
    use: true
    token: 'the coolest token'
staffmode:
  resetgamemode: true
  tptospawn:
    teleport: true
    use-spawn-cmd: false
    spawn-cmd: 'spawn'
    location:
      world: 'world'
      coordinates:
        x: 12.0
        y: 8.0
        z: 0.0
        yaw: -90
        pitch: 0
  pseudodisconnect:
    send-message: true
    message: '&e%p% left the game.'
  pseudojoin:
    send-message: true
    message: '&e%p% joined the game.'
  #"Tempban-length" is in days, and "mute-length" is in minutes.
  punishment:
    report:
      reasons:
        1: 'Cheating'
        2: 'Chat Abuse'
        3: 'idk fookin botum geah moates'
        4: 'Chargebacks'
        5: 'DDoS Threats'
        6: 'Name Abuse'
        7: 'Player Threats'
        8: ''
    ban:
      reasons:
        1: 'Cheating'
        2: 'Chat Abuse'
        3: 'idk fookin botum geah moates'
        4: 'Chargebacks'
        5: 'DDoS Threats'
        6: 'Name Abuse'
        7: 'Player Threats'
        8: ''
      tempban-length: 30
      ip-ban: true
    mute:
      reason: 'Chat Abuse'
      mute-length: 30
  stats:
    api-key: 'your api key'
    public-networks: false
    strict: true
#Protect-sensitive will hide the ip and port from anyone without the "admincore.admin" permission
serverstatus:
  protect-sensitive: true
  serverVersion:
    log: true
  buildInformation:
    log: true
  ip:
    log: true
  port:
    log: true
  playerCount:
    log: true
  tps:
    log:
      one-minute: true
      five-minutes: true
      fifteen-minutes: true
  uptime:
    log: true
  ram:
    log: true
  ping:
    log: true
