name: Auto Port

on:
  workflow_dispatch:

jobs:
  port:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge 1.12
        uses: everlytic/branch-merge@1.1.2
        with:
          source_ref: "1.16"
          target_branch: "1.12"
      - name: Merge 1.13
        uses: everlytic/branch-merge@1.1.2
        with:
          source_ref: "1.16"
          target_branch: "1.13"
      - name: Merge 1.14
        uses: everlytic/branch-merge@1.1.2
        with:
          source_ref: "1.16"
          target_branch: "1.14"
      - name: Merge 1.15
        uses: everlytic/branch-merge@1.1.2
        with:
          source_ref: "1.16"
          target_branch: "1.15"
      - name: Merge 1.16
        uses: everlytic/branch-merge@1.1.2
        with:
          source_ref: "1.16"
          target_branch: "1.17"
  
  build-12:
    
    needs: port
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: "1.12"
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B clean package --file pom.xml
  
  build-13:
    
    needs: port
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: "1.13"
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B clean package --file pom.xml
  
  build-14:
    
    needs: port
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: "1.14"
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B clean package --file pom.xml
  
  build-15:
    
    needs: port
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: "1.15"
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B clean package --file pom.xml
  
  build-17:
    
    needs: port
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: "1.17"
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B clean package --file pom.xml
